# Generated by Django 5.1 on 2024-10-19 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_alter_customuser_options_categorymodel_taskmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['username'], 'verbose_name': 'CustomUser'},
        ),
        migrations.AlterModelTable(
            name='customuser',
            table='my_to_do_list_table',
        ),
    ]
