# Generated by Django 5.1 on 2024-10-19 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_alter_customuser_options_alter_customuser_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['username'], 'verbose_name': 'CustomUser', 'verbose_name_plural': 'CustomUsers'},
        ),
        migrations.AlterUniqueTogether(
            name='customuser',
            unique_together={('username', 'email')},
        ),
        migrations.AlterUniqueTogether(
            name='taskmodel',
            unique_together={('category', 'TaskName')},
        ),
    ]
