# Generated by Django 5.1 on 2024-10-19 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskmodel',
            old_name='Date',
            new_name='completed_date',
        ),
        migrations.AddField(
            model_name='categorymodel',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='categorymodel',
            name='updated_at',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='taskmodel',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='taskmodel',
            name='descriptions',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='taskmodel',
            name='due_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='taskmodel',
            name='proirity',
            field=models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='taskmodel',
            name='status',
            field=models.CharField(default='on_Going', max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='BasicInfoModel',
        ),
    ]
